Refine new version detection
* Branch name is user controled data. Store value in environment vatiable insteald of directly using expression.
* Use regex to extract semver value
* Replace deprecated method of setting output variables
* Set permission on step instead of using a personal access token

diff --git a/.github/workflows/detect_version_bump.yml b/.github/workflows/detect_version_bump.yml
--- a/.github/workflows/detect_version_bump.yml
+++ b/.github/workflows/detect_version_bump.yml
@@ -24,22 +24,31 @@ jobs:
         startsWith(github.event.pull_request.title, 'Bump version') &&
         contains(github.event.pull_request.title, ' → ')
     environment: Create Release
+    permissions:
+      contents: write
     steps:
       - name: Get new version
         id: get-new-version
+        env:
+          MERGED_BRANCH_NAME: ${{ github.head_ref }}
         run: |
-          NEW_VERSION=$(echo ${{ github.head_ref }} | cut -d _ -f4 )
-          echo "::set-output name=version::$NEW_VERSION"
+          if [[ "${MERGED_BRANCH_NAME}" =~ ^bump_version_to_([0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?)$ ]]; then
+            NEW_VERSION=${BASH_REMATCH[1]}
+            echo "::debug::New version=\"${NEW_VERSION}\""
+            echo "version=${NEW_VERSION}" >> "${GITHUB_OUTPUT}"
+          else
+            echo "::error::New version not found in \"${MERGED_BRANCH_NAME}\""
+            exit 1
+          fi
       - name: Is prerelease?
         id: is-prerelease
         run: |
           IS_PRERELEASE=$([[ "${{ steps.get-new-version.outputs.version }}" == *-[a-z]* ]] && echo true || echo false)
-          echo "::set-output name=result::$IS_PRERELEASE"
+          echo "result=${NEW_VERSION}" >> "${GITHUB_OUTPUT}"
       - name: Create Release
         # use hash for security since this has access to the access token
         uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
         with:
-          token: ${{ secrets.DEPLOY_TOKEN }}
           tag: v${{ steps.get-new-version.outputs.version }}
           name: v${{ steps.get-new-version.outputs.version }} Release
           commit: main
